### ISSUE TITLE
Semi-global alignment ratio?

### ISSUE THREAD

**Issue by jianshu93** [ocxtal/adaptivebandbench#2]
Hello Team,

I have long reads from PacBio (1k to 15k), I want to align them in some pairs and they can be highly similar, e.g., > 90% sequence identity but only for the overlapped region, meaning, 2 sequences might only have 50% aligned, and the aligned region is very high identity, which means I need semi-global alignment, I need to know the aligned length (so that I can calculate the alignment ratio). It would be nice if I can also detect a little bit below 90% identity, e.g., 85%. I do not recall where block aligner can do semi-global alignment, that is the gaps opened at both ends will not be penalized (or a very small penalty score like in vsearch --all_pairs_global, but those low penalty gaps will not be in the final alignment). Also read the adaptive banded aligner paper, still not sure how to compute the aligned ratio (e.g., aligned positions/query length). I guess both adaptive banded DB and block aligner can be adapted to compute the semi-global alignment alignment ratio and identity for the aligned region? This is what needed in real world application. Any suggestions? Let me know if I am not clear.

Thanks,

Jianshu

**Comment by ocxtal** [comment]
first of all, your question looks not related to this repository. the repository is for providing resources to reproduce our benchmark. please ask your question somewhere more appropriate.

**Comment by ocxtal** [comment]
brief suggestion: alignment identity can be calculated from alignment path, because path has complete match/mismatch/gap information. in general, all practical alignment library returns path information (at least when specified to compute it), so in theory, you can compute alignment identity using any library you like. it's irrelevant to how (that is, by local or semi-global or global) the alignment path is computed.
